os:
  - linux
  - osx
language: generic
env:
  global:
  - SWIFT_VERSION=3.1

sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

dist: trusty

osx_image: xcode8

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "$(cat ./install-swiftenv.sh)";
      sudo apt-get install -y libcurl4-openssl-dev libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev libbsd-dev;
      sudo rm /usr/bin/ld && sudo ln -s /usr/bin/ld.gold /usr/bin/ld;
    fi

script:
  - swift package clean # clean built artifacts if present
  - swift package fetch # clones all dependencies
  - swift build # build project
  - swift test #run tests
